export const workData = [
  {
    id: 1,
    title: "Work Shift",
    name: "Kitchen",
    start: "6:00 AM",
    end: "1:45 PM",
    location: "Aegis",
    rate: 32.5,
  },
  {
    id: 2,
    title: "Work Shift",
    name: "Kitchen",
    start: "7:00 AM",
    end: "3:00 PM",
    location: "Aegis",
    rate: 32.5,
  },
  {
    id: 3,
    title: "Work Shift",
    name: "Kitchen",
    start: "5:30 AM",
    end: "12:30 PM",
    location: "Aegis",
    rate: 34.0,
  },
  {
    id: 4,
    title: "Work Shift",
    name: "Kitchen",
    start: "8:00 AM",
    end: "4:15 PM",
    location: "Aegis",
    rate: 33.25,
  },
  {
    id: 5,
    title: "Work Shift",
    name: "Kitchen",
    start: "6:15 AM",
    end: "2:00 PM",
    location: "Aegis",
    rate: 32.5,
  },
];
